# Generated by Django 4.0.4 on 2022-04-26 00:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=api.models.User.nameFile, validators=[api.models.User.file_size]),
        ),
    ]
