# Generated by Django 4.0.4 on 2022-04-27 14:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=api.models.User.nameFile, validators=[api.models.User.file_size]),
        ),
    ]
