# Generated by Django 4.0.4 on 2022-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='institution_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
