# Generated by Django 4.0.4 on 2022-06-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_institution_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'get_latest_by': ('updated_at', 'created_at'), 'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': ('updated_at', 'created_at'), 'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': ('tran_date', 'updated_at', 'created_at'), 'ordering': ('-tran_date', '-updated_at', '-created_at')},
        ),
    ]
