# Generated by Django 4.0.4 on 2022-07-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': ('tran_date', 'created_at', 'updated_at'), 'ordering': ('-tran_date', '-created_at', '-updated_at')},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('score', models.FloatField()),
                ('inflow', models.BigIntegerField()),
                ('outflow', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month', 'bank_account', 'user'),
                'unique_together': {('bank_account', 'month')},
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
