# Generated by Django 4.0.4 on 2022-09-06 14:11

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transactions',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
