# Generated by Django 4.0.4 on 2022-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transactions_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='re_auth_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
