# Generated by Django 4.0.4 on 2022-09-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transactions_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
