# Generated by Django 4.1.1 on 2022-09-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_transactions_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': ('tran_date', 'created_at'), 'ordering': ('-tran_date', '-created_at')},
        ),
    ]
