# Generated by Django 4.1.1 on 2022-10-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_transactions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
